const products=[
 {name:'Premium Oversized Black',category:'Oversized',price:250,old:320,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85'},
 {name:'Vintage Washed Graphic',category:'Vintage',price:280,old:350,image:'https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=85'},
 {name:'Minimal White Essential',category:'Minimal',price:250,old:300,image:'https://images.unsplash.com/photo-1521572179197-9c2b31b95f4c?auto=format&fit=crop&w=900&q=85'},
 {name:'Anime Street Oversized',category:'Graphic',price:320,old:390,image:'https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=900&q=85'}
];
let cart=0;const $=id=>document.getElementById(id);const grid=$('productGrid');
function toast(text){const el=$('toast');el.textContent=text;el.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.hidden=true,2200)}
function add(name){cart++;$('bagCount').textContent=cart;toast(name+' added to your inquiry')}
function render(query=''){const list=products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(query.toLowerCase()));grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image" style="background-image:url('${p.image}')"><span>${p.category}</span><button aria-label="Save ${p.name}">♡</button></div><div class="product-body"><p>${p.category}</p><h3>${p.name}</h3><div><strong>₱${p.price}</strong><del>₱${p.old}</del><button data-add="${p.name}">Add +</button></div></div></article>`).join('');$('noResults').hidden=!!list.length;grid.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add))}
function updateQuote(){let qty=Math.max(20,Number($('quantity').value)||20);$('quantity').value=qty;let style=$('style').value,sides=$('sides').value;let unit=250+(style==='Dry Fit'?35:style==='Classic Tee'?-20:0)+(sides==='Front + Back'?55:0)-(qty>=100?35:qty>=50?20:0);$('cardQty').textContent=qty;$('cardStyle').textContent=style;$('cardPrice').textContent=unit;$('cardTotal').textContent=(unit*qty).toLocaleString();$('estimate').innerHTML=`Get ₱${unit}/pc estimate <span>→</span>`}
$('search').oninput=e=>render(e.target.value);$('style').onchange=updateQuote;$('sides').onchange=updateQuote;$('quantity').oninput=updateQuote;$('minus').onclick=()=>{$('quantity').value=Math.max(20,Number($('quantity').value)-10);updateQuote()};$('plus').onclick=()=>{$('quantity').value=Number($('quantity').value)+10;updateQuote()};document.querySelectorAll('.swatch').forEach(s=>s.onclick=()=>{document.querySelectorAll('.swatch').forEach(x=>x.classList.remove('active'));s.classList.add('active')});document.querySelectorAll('.add-order').forEach(b=>b.onclick=()=>add($('quantity').value+'× '+$('style').value));$('bag').onclick=()=>toast(cart?cart+' item'+(cart>1?'s':'')+' in your inquiry':'Your inquiry is empty');render();updateQuote();
